repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer  # Ensures there's a newline at the end of the file
      - id: trailing-whitespace  # Removes unnecessary trailing spaces

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args:
        - --line-length=150
        - --target-version=py313
        - --skip-string-normalization
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E203,E501,E266,F541,W503

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Unit Tests with Coverage
        entry: poetry run pytest --cov=source --cov-fail-under=80
        language: system
        pass_filenames: false
        args: ["tests"]
