name: UnitTests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: python -m pytest -rA -sv tests/test_app.py
